import type { WaterSite } from './siteData';

/** Reference markers for major Tamil Nadu rivers and water bodies (atlas guide pins) */
export const MAJOR_WATER_GUIDE_SITES: WaterSite[] = [
  {
    id: 'guide-kaveri',
    name: 'Kaveri River',
    coords: [10.79, 78.68],
    type: 'River',
    guide: true,
    story: 'The great river of central Tamil Nadu, lifeline of the delta districts.',
  },
  {
    id: 'guide-tamiraparani',
    name: 'Tamiraparani River',
    coords: [8.65, 77.85],
    type: 'River',
    guide: true,
    story: 'Porunai / Thamirabarani, ancestral river of the far south.',
  },
  {
    id: 'guide-vaigai',
    name: 'Vaigai River',
    coords: [9.93, 78.12],
    type: 'River',
    guide: true,
    story: 'Flows through Madurai and the Pandya heartland.',
  },
  {
    id: 'guide-palar',
    name: 'Palar River',
    coords: [12.85, 79.72],
    type: 'River',
    guide: true,
    story: 'Eastern river forming part of the northern Tamil Nadu border.',
  },
  {
    id: 'guide-pennar',
    name: 'Pennar River',
    coords: [12.02, 79.55],
    type: 'River',
    guide: true,
    story: 'Ponnaiyar basin river between Tamil Nadu and Andhra Pradesh.',
  },
  {
    id: 'guide-bhavani',
    name: 'Bhavani River',
    coords: [11.45, 77.0],
    type: 'River',
    guide: true,
    story: 'Major Kaveri tributary from the Western Ghats.',
  },
  {
    id: 'guide-amaravathi',
    name: 'Amaravathi River',
    coords: [10.85, 77.35],
    type: 'River',
    guide: true,
    story: 'Western Ghats tributary feeding the Kaveri system.',
  },
  {
    id: 'guide-noyyal',
    name: 'Noyyal River',
    coords: [11.05, 77.0],
    type: 'River',
    guide: true,
    story: 'Kongu region river linked to tanks and textile towns.',
  },
  {
    id: 'guide-thenpennai',
    name: 'Thenpennai River',
    coords: [12.0, 79.35],
    type: 'River',
    guide: true,
    story: 'South Pennar system river in northern Tamil Nadu.',
  },
  {
    id: 'guide-kollidam',
    name: 'Kollidam River',
    coords: [11.0, 79.55],
    type: 'River',
    guide: true,
    story: 'Kaveri distributary carrying flood waters to the east.',
  },
  {
    id: 'guide-gundar',
    name: 'Gundar River',
    coords: [9.35, 78.85],
    type: 'River',
    guide: true,
    story: 'Southern river of the Ramanathapuram and Sivaganga region.',
  },
  {
    id: 'guide-vaippar',
    name: 'Vaippar River',
    coords: [9.45, 78.1],
    type: 'River',
    guide: true,
    story: 'Flows through Tuticorin and Virudhunagar districts.',
  },
  {
    id: 'guide-pulicat',
    name: 'Pulicat Lake',
    coords: [13.55, 80.2],
    type: 'Lake',
    guide: true,
    story: 'Second largest brackish water lagoon on the Coromandel coast.',
  },
  {
    id: 'guide-veeranam',
    name: 'Veeranam Lake',
    coords: [11.55, 79.52],
    type: 'Lake',
    guide: true,
    story: 'Ancient Chola tank still linked to Chennai water supply.',
  },
  {
    id: 'guide-mettur',
    name: 'Mettur Reservoir',
    coords: [11.82, 77.8],
    type: 'Reservoir',
    guide: true,
    story: 'Stanley Reservoir on the Kaveri at the Salem gorge.',
  },
  {
    id: 'guide-pykara',
    name: 'Pykara Lake',
    coords: [11.45, 76.55],
    type: 'Lake',
    guide: true,
    story: 'Nilgiri hill lake and reservoir above Ooty.',
  },
  {
    id: 'guide-berijam',
    name: 'Berijam Lake',
    coords: [10.19, 77.33],
    type: 'Lake',
    guide: true,
    story: 'Highland reservoir in the Palani Hills near Kodaikanal.',
  },
  {
    id: 'guide-red-hills',
    name: 'Red Hills Lake',
    coords: [13.17, 80.15],
    type: 'Lake',
    guide: true,
    story: 'Major rain-fed reservoir serving Chennai.',
  },
  {
    id: 'guide-ooty',
    name: 'Ooty Lake',
    coords: [11.41, 76.69],
    type: 'Lake',
    guide: true,
    story: 'Colonial-era lake in the Nilgiri hill station.',
  },
  {
    id: 'guide-cooum',
    name: 'Cooum River',
    coords: [13.08, 80.27],
    type: 'River',
    guide: true,
    story: 'Urban river running through Chennai.',
  },
];
